image: docker:latest

services:
  - docker:dind

before_script:
  - apk add --no-cache py-pip python-dev libffi-dev openssl-dev gcc libc-dev make
  - pip install docker-compose

stages:
  - build
  - test
  - quality

testCheck:
  stage: test
  script:
    - docker-compose run app /bin/sh -c "cd /app; npm i; npm run test"
  coverage:
    '/Statements.*?(\d+(?:\.\d+)?)%/'